-
  name: 'NeosRulez.DirectMail create recipient'
  uriPattern: 'subscribe'
  defaults:
    '@controller': 'Subscription'
    '@package': 'NeosRulez.DirectMail'
    '@action': 'create'
  appendExceedingArguments: true
-
  name: 'NeosRulez.DirectMail set active'
  uriPattern: 'setactive/{identifier}'
  defaults:
    '@controller': 'Subscription'
    '@package': 'NeosRulez.DirectMail'
    '@action': 'setActive'
  appendExceedingArguments: true
-
  name: 'NeosRulez.DirectMail unsubscribe'
  uriPattern: 'unsubscribe/{identifier}'
  defaults:
    '@controller': 'Subscription'
    '@package': 'NeosRulez.DirectMail'
    '@action': 'unsubscribe'
  appendExceedingArguments: true
-
  name: 'NeosRulez.DirectMail unsubscribe recipient'
  uriPattern: 'unsubscriberecipient'
  defaults:
    '@controller': 'Subscription'
    '@package': 'NeosRulez.DirectMail'
    '@action': 'unsubscribeRecipient'
  appendExceedingArguments: true
-
  name: 'NeosRulez.DirectMail render html'
  uriPattern: 'directmail/{base64Uri}'
  defaults:
    '@controller': 'Newsletter'
    '@package': 'NeosRulez.DirectMail'
    '@action': 'index'
  appendExceedingArguments: true
-
  name: 'NeosRulez.DirectMail tracking'
  uriPattern: 'tracking/{queue}/{recipient}/{action}/{description}'
  defaults:
    '@controller': 'Tracking'
    '@package': 'NeosRulez.DirectMail'
    '@action': 'create'
  appendExceedingArguments: true
-
  name: 'NeosRulez.DirectMail recipient ajax loading'
  uriPattern: 'index'
  defaults:
    '@controller': 'Recipient'
    '@package': 'NeosRulez.DirectMail'
    '@action': 'index'
  appendExceedingArguments: true

-
  name: 'NeosRulez.DirectMail api'
  uriPattern: 'directmail/api/import'
  defaults:
    '@controller': 'Api'
    '@package': 'NeosRulez.DirectMail'
    '@action': 'import'
  appendExceedingArguments: true