Neos:
  Flow:
    mvc:
      routes:
        'NeosRulez.DirectMail': true
  Neos:
    fusion:
      autoInclude:
        NeosRulez.DirectMail: true
    userInterface:
      translation:
        autoInclude:
          NeosRulez.DirectMail:
            - Main
            - 'NodeTypes/*'
            - 'Integration/*'
            - 'Presentation/*'
            - 'Mail/*'
    nodeTypes:
      groups:
        neosRulezDirectMail:
          position: 'end'
          label: NeosRulez.DirectMail:Main:group.content
        neosRulezDirectMailForm:
          position: 'after neosRulezDirectMail'
          label: NeosRulez.DirectMail:Main:group.form
    modules:
      directMail:
        label: 'DirectMail'
        controller: '\Neos\Neos\Controller\Module\ManagementController'
        description: 'DirectMail'
        icon: 'far fa-paper-plane'
        resource: 'Neos_Neos_Backend_Module_Management'
        submodules:
#          recipient:
#            label: NeosRulez.DirectMail:Integration.Controller.Recipient:label
#            controller: '\NeosRulez\DirectMail\Controller\RecipientController'
#            description: NeosRulez.DirectMail:Integration.Controller.Recipient:description
#            icon: 'fas fa-user-friends'
#            actions:
#              index:
#                label: NeosRulez.DirectMail:Integration.Controller.Recipient:label
#                title: NeosRulez.DirectMail:Integration.Controller.Recipient:label
#            additionalResources:
#              javaScripts:
#                - 'resource://NeosRulez.DirectMail/Public/JavaScript/jquery-3.6.0.min.js'
          recipientlist:
            label: NeosRulez.DirectMail:Integration.Controller.RecipientList:label
            controller: '\NeosRulez\DirectMail\Controller\RecipientListController'
            description: NeosRulez.DirectMail:Integration.Controller.RecipientList:description
            icon: 'fas fa-envelope-open-text'
            actions:
              index:
                label: NeosRulez.DirectMail:Integration.Controller.RecipientList:label
                title: NeosRulez.DirectMail:Integration.Controller.RecipientList:label
            additionalResources:
              javaScripts:
                - 'resource://NeosRulez.DirectMail/Public/JavaScript/jquery-3.6.0.min.js'
          queue:
            label: NeosRulez.DirectMail:Integration.Controller.Queue:label
            controller: '\NeosRulez\DirectMail\Controller\QueueController'
            description: NeosRulez.DirectMail:Integration.Controller.Queue:description
            icon: 'far fa-clock'
            actions:
              index:
                label: NeosRulez.DirectMail:Integration.Controller.Queue:label
                title: NeosRulez.DirectMail:Integration.Controller.Queue:label
              tracking:
                label: NeosRulez.DirectMail:Integration.Controller.Tracking:label
                title: NeosRulez.DirectMail:Integration.Controller.Tracking:description
            additionalResources:
              javaScripts:
                - 'resource://NeosRulez.DirectMail/Public/JavaScript/jquery-3.6.0.min.js'
          tracking:
            label: NeosRulez.DirectMail:Integration.Controller.Tracking:label
            controller: '\NeosRulez\DirectMail\Controller\TrackingController'
            description: NeosRulez.DirectMail:Integration.Controller.Tracking:description
            icon: 'fas fa-chart-bar'
            actions:
              index:
                label: NeosRulez.DirectMail:Integration.Controller.Tracking:label
                title: NeosRulez.DirectMail:Integration.Controller.Tracking:label
            additionalResources:
              javaScripts:
                - 'resource://NeosRulez.DirectMail/Public/JavaScript/jquery-3.6.0.min.js'
          import:
            label: NeosRulez.DirectMail:Integration.Controller.Import:label
            controller: '\NeosRulez\DirectMail\Controller\ImportController'
            description: NeosRulez.DirectMail:Integration.Controller.Import:description
            icon: 'fas fa-file-csv'
            actions:
              index:
                label: NeosRulez.DirectMail:Integration.Controller.Import:label
                title: NeosRulez.DirectMail:Integration.Controller.Import:label
            additionalResources:
              javaScripts:
                - 'resource://NeosRulez.DirectMail/Public/JavaScript/jquery-3.6.0.min.js'
#NeosRulez:
#  DirectMail:
#    useAjax: false
#    senderMail: 'postmaster@foo.bar'
#    senderName: 'Postmaster'
#    startDispatchFromNeosBackend: false
#    baseUri: 'http://foo.bar'
#    apiKey: '12345678' # Use a safe key with random letters and numbers in sufficient length
#    percentageOfDispatch: true
#    language: true
#    rtrEcgList:
#      apiKey: 'bc3e81d8-5673-444d-a373-67954417786a' # When creating mailings, you can check whether the recipients are on the ecg list. These recipients will not be added.
#    recipient:
#      customFields:
#        company:
#          type: string
#          label: Company
